[build]
  functions= "functions"
  command = "npm run build"
  publish = "build"

[dev]
  command = "npm start"
  functions = "functions" 
  publish = "build"
  port=3000 
  targetPort=8080 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200